using System.Text;
using RonSijm.RepoGen.Design;

namespace RonSijm.RepoGen.Tool;

internal static class ProjectionSourceRenderer
{
    public static string Render(RepositoryGenerationModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");

        var groups = model.Entities
            .SelectMany(entity => entity.Projections.Select(projection => new { Entity = entity, Projection = projection }))
            .GroupBy(
                static item => new { item.Projection.Namespace, item.Entity.EntityName },
                static item => item)
            .OrderBy(static group => group.Key.Namespace, StringComparer.Ordinal)
            .ThenBy(static group => group.Key.EntityName, StringComparer.Ordinal);

        foreach (var group in groups)
        {
            builder.AppendLine();
            if (!string.IsNullOrEmpty(group.Key.Namespace))
            {
                builder.Append("namespace ").Append(group.Key.Namespace).AppendLine();
                builder.AppendLine("{");
            }

            var indentation = string.IsNullOrEmpty(group.Key.Namespace) ? string.Empty : "    ";
            var entity = group.First().Entity;
            builder.Append(indentation).Append(entity.Accessibility).Append(" static class ").Append(entity.EntityName)
                .AppendLine("ConfiguredProjectionExtensions");
            builder.Append(indentation).AppendLine("{");

            foreach (var item in group.OrderBy(static item => item.Projection.SingleMethodName, StringComparer.Ordinal))
            {
                AppendProjectionMethods(builder, item.Entity, item.Projection, indentation + "    ");
            }

            builder.Append(indentation).AppendLine("}");
            if (!string.IsNullOrEmpty(group.Key.Namespace))
            {
                builder.AppendLine("}");
            }
        }

        AppendConfiguredQueries(builder, model);

        return builder.ToString();
    }

    private static void AppendConfiguredQueries(StringBuilder builder, RepositoryGenerationModel model)
    {
        var groups = model.Entities
            .SelectMany(entity => entity.Queries.Select(query => new { Entity = entity, Query = query }))
            .GroupBy(
                static item => new { item.Query.Namespace, item.Entity.EntityName },
                static item => item)
            .OrderBy(static group => group.Key.Namespace, StringComparer.Ordinal)
            .ThenBy(static group => group.Key.EntityName, StringComparer.Ordinal);

        foreach (var group in groups)
        {
            builder.AppendLine();
            if (!string.IsNullOrEmpty(group.Key.Namespace))
            {
                builder.Append("namespace ").Append(group.Key.Namespace).AppendLine();
                builder.AppendLine("{");
            }

            var indentation = string.IsNullOrEmpty(group.Key.Namespace) ? string.Empty : "    ";
            var entity = group.First().Entity;
            builder.Append(indentation).Append(entity.Accessibility).Append(" static class ")
                .Append(entity.EntityName).AppendLine("ConfiguredQueryExtensions");
            builder.Append(indentation).AppendLine("{");
            foreach (var item in group.OrderBy(static item => item.Query.MethodName, StringComparer.Ordinal))
            {
                AppendConfiguredQuery(builder, item.Entity, item.Query, indentation + "    ");
            }

            builder.Append(indentation).AppendLine("}");
            if (!string.IsNullOrEmpty(group.Key.Namespace))
            {
                builder.AppendLine("}");
            }
        }
    }

    private static void AppendConfiguredQuery(
        StringBuilder builder,
        EntityRepositoryModel entity,
        ConfiguredQueryModel query,
        string indentation)
    {
        var repository = Qualify(entity.Namespace, "I" + entity.EntityName + "Repository");
        var cacheableRepository = Qualify(entity.Namespace, "ICacheable" + entity.EntityName + "Repository");
        var returnType = RenderQueryReturnType(query);
        var parameters = CreateQueryParameters(query);
        var argumentNames = parameters.Select(static parameter => parameter.Name).ToArray();
        var accessibility = entity.Accessibility == "public" && query.Accessibility == "public"
            ? "public"
            : "internal";

        builder.Append(indentation).Append(accessibility).Append(" static ").Append(returnType).Append(' ')
            .Append(query.MethodName).AppendLine("(");
        builder.Append(indentation).Append("    this ").Append(repository).AppendLine(" repository,");
        AppendMethodParameters(builder, parameters, indentation + "    ", includeCancellationToken: true);
        builder.Append(indentation).AppendLine(")");
        builder.Append(indentation).AppendLine("{");
        builder.Append(indentation).AppendLine("    if (repository is null)");
        builder.Append(indentation).AppendLine("    {");
        builder.Append(indentation).AppendLine("        throw new global::System.ArgumentNullException(nameof(repository));");
        builder.Append(indentation).AppendLine("    }");

        if (query.Cache.Enabled)
        {
            builder.AppendLine();
            builder.Append(indentation).Append("    if (repository is ").Append(cacheableRepository)
                .AppendLine(" cacheableRepository)");
            builder.Append(indentation).AppendLine("    {");
            builder.Append(indentation).Append("        var cacheKey = \"").Append(EscapeString(query.MethodName)).AppendLine(":\" +");
            builder.Append(indentation).Append("            global::System.Text.Json.JsonSerializer.Serialize(new object?[] { ")
                .Append(string.Join(", ", argumentNames)).AppendLine(" });");
            builder.Append(indentation).AppendLine("        return cacheableRepository.GetOrCreateCachedAsync(");
            builder.Append(indentation).AppendLine("            cacheKey,");
            builder.Append(indentation).Append("            ").Append(RenderCacheOptions(query.Cache)).AppendLine(",");
            builder.Append(indentation).Append("            (source, token) => ").Append(query.MethodName)
                .Append("Core(source");
            foreach (var argument in argumentNames)
            {
                builder.Append(", ").Append(argument);
            }

            builder.AppendLine(", token),");
            builder.Append(indentation).AppendLine("            cancellationToken);");
            builder.Append(indentation).AppendLine("    }");
        }

        builder.AppendLine();
        builder.Append(indentation).Append("    return ").Append(query.MethodName).Append("Core(repository");
        foreach (var argument in argumentNames)
        {
            builder.Append(", ").Append(argument);
        }

        builder.AppendLine(", cancellationToken);");
        builder.Append(indentation).AppendLine("}");
        builder.AppendLine();

        builder.Append(indentation).Append("private static ").Append(returnType).Append(' ').Append(query.MethodName)
            .AppendLine("Core(");
        builder.Append(indentation).Append("    ").Append(repository).AppendLine(" repository,");
        AppendMethodParameters(builder, parameters, indentation + "    ", includeCancellationToken: true);
        builder.Append(indentation).AppendLine(")");
        builder.Append(indentation).AppendLine("{");
        builder.Append(indentation).AppendLine("    var selector = repository.GetAll();");
        foreach (var predicate in query.Predicates)
        {
            builder.Append(indentation).Append("    selector = selector.Where(entity => ")
                .Append(predicate.PredicateSource).AppendLine(");");
        }

        foreach (var include in query.Includes)
        {
            builder.Append(indentation).Append("    selector = selector.Include(")
                .Append(include.ExpressionSource).AppendLine(");");
        }

        for (var index = 0; index < query.Sorts.Count; index++)
        {
            var sort = query.Sorts[index];
            var method = index == 0
                ? sort.IsDescending ? "OrderByDescending" : "OrderBy"
                : sort.IsDescending ? "ThenByDescending" : "ThenBy";
            builder.Append(indentation).Append("    selector = selector.").Append(method).Append('(')
                .Append(sort.ExpressionSource).AppendLine(");");
        }

        if (query.DynamicSort is not null)
        {
            builder.Append(indentation).Append("    if (");
            for (var index = 0; index < query.DynamicSort.Fields.Count; index++)
            {
                if (index > 0)
                {
                    builder.Append(" && ");
                }

                builder.Append("!global::System.String.Equals(")
                    .Append(query.DynamicSort.FieldNameParameter).Append(", \"")
                    .Append(EscapeString(query.DynamicSort.Fields[index].PropertyName))
                    .Append("\", global::System.StringComparison.OrdinalIgnoreCase)");
            }

            builder.AppendLine(")");
            builder.Append(indentation).AppendLine("    {");
            builder.Append(indentation).Append("        throw new global::System.ArgumentOutOfRangeException(nameof(")
                .Append(query.DynamicSort.FieldNameParameter).Append("), ")
                .Append(query.DynamicSort.FieldNameParameter).Append(", \"Sortable fields for this query: ")
                .Append(string.Join(", ", query.DynamicSort.Fields.Select(static field => field.PropertyName)))
                .AppendLine(".\");");
            builder.Append(indentation).AppendLine("    }");
            builder.Append(indentation).Append("    selector = selector.OrderBy(")
                .Append(query.DynamicSort.FieldNameParameter).Append(", ")
                .Append(query.DynamicSort.DescendingParameter).AppendLine(");");
        }

        AppendQueryPolicies(builder, query, indentation + "    ");

        if (query.ResultKind == RepositoryQueryResultKind.CursorPaged)
        {
            builder.Append(indentation).AppendLine("    if (cursorPage.HasCursor)");
            builder.Append(indentation).AppendLine("    {");
            builder.Append(indentation).AppendLine("        var cursor = cursorPage.Cursor!;");
            builder.Append(indentation).Append("        selector = selector.Where(entity => ")
                .Append(query.Cursor!.SeekPredicateBodySource).AppendLine(");");
            builder.Append(indentation).AppendLine("    }");
            builder.AppendLine();
        }

        builder.Append(indentation).Append("    return ").Append(RenderQueryTerminal(entity, query)).AppendLine(";");
        builder.Append(indentation).AppendLine("}");
        builder.AppendLine();
    }

    private static void AppendQueryPolicies(StringBuilder builder, ConfiguredQueryModel query, string indentation)
    {
        var trackingMethod = query.TrackingBehavior switch
        {
            RepositoryTrackingBehavior.Tracking => "AsTracking",
            RepositoryTrackingBehavior.NoTracking => "AsNoTracking",
            RepositoryTrackingBehavior.NoTrackingWithIdentityResolution => "AsNoTrackingWithIdentityResolution",
            _ => null
        };
        if (trackingMethod is not null)
        {
            builder.Append(indentation).Append("selector = selector.").Append(trackingMethod).AppendLine("();");
        }

        if (query.IgnoreQueryFilters)
        {
            builder.Append(indentation).AppendLine("selector = selector.ConfigureQuery(static source => global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.IgnoreQueryFilters(source));");
        }

        if (query.SplittingBehavior != RepositoryQuerySplittingBehavior.Unspecified)
        {
            var method = query.SplittingBehavior == RepositoryQuerySplittingBehavior.SplitQuery
                ? "AsSplitQuery"
                : "AsSingleQuery";
            builder.Append(indentation).Append("selector = selector.ConfigureQuery(static source => global::Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.")
                .Append(method).AppendLine("(source));");
        }

        if (query.QueryTag is not null)
        {
            builder.Append(indentation).Append("selector = selector.ConfigureQuery(static source => global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.TagWith(source, \"")
                .Append(EscapeString(query.QueryTag)).AppendLine("\"));");
        }
    }

    private static string RenderQueryTerminal(EntityRepositoryModel entity, ConfiguredQueryModel query)
    {
        var cancellation = "cancellationToken";
        var selector = entity.ProjectionEnabled
            ? "selector"
            : $"((global::RonSijm.RepoGen.BaseCollectionSelector<{entity.EntityTypeName}>)selector)";
        return query.ResultKind switch
        {
            RepositoryQueryResultKind.List => $"{selector}.ProjectToListAsync({query.ProjectionExpressionSource}, {cancellation})",
            RepositoryQueryResultKind.Single => $"{selector}.ProjectToSingleAsync({query.ProjectionExpressionSource}, {cancellation})",
            RepositoryQueryResultKind.SingleOrDefault => $"{selector}.ProjectToSingleOrDefaultAsync({query.ProjectionExpressionSource}, {cancellation})",
            RepositoryQueryResultKind.FirstOrDefault => $"{selector}.ProjectToFirstOrDefaultAsync({query.ProjectionExpressionSource}, {cancellation})",
            RepositoryQueryResultKind.Paged => $"{selector}.ToPagedListAsync({query.ProjectionExpressionSource}, page, pageSize, {cancellation})",
            RepositoryQueryResultKind.CursorPaged => $"{selector}.ToCursorPagedListAsync({query.ProjectionExpressionSource}, {query.Cursor!.CursorSelectorExpressionSource}, cursorPage.PageSize, {cancellation})",
            RepositoryQueryResultKind.GroupedList => $"{selector}.GroupBy({query.Group!.KeySelectorExpressionSource}).ProjectToListAsync({query.Group.ProjectionExpressionSource}, {cancellation})",
            RepositoryQueryResultKind.Exists => $"{Qualify(entity.Namespace, entity.EntityName + "CollectionSelectorExtensions")}.ExistsAsync(selector, {cancellation})",
            RepositoryQueryResultKind.Count => $"{Qualify(entity.Namespace, entity.EntityName + "CollectionSelectorExtensions")}.CountAsync(selector, {cancellation})",
            RepositoryQueryResultKind.Stream => $"{selector}.StreamAsync({query.ProjectionExpressionSource}, {cancellation})",
            _ => throw new InvalidOperationException($"Unsupported configured query result kind '{query.ResultKind}'.")
        };
    }

    private static string RenderQueryReturnType(ConfiguredQueryModel query) => query.ResultKind switch
    {
        RepositoryQueryResultKind.List => $"global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<{query.ResultTypeName}>>",
        RepositoryQueryResultKind.Single => $"global::System.Threading.Tasks.Task<{query.ResultTypeName}>",
        RepositoryQueryResultKind.SingleOrDefault or RepositoryQueryResultKind.FirstOrDefault =>
            $"global::System.Threading.Tasks.Task<{query.ResultTypeName}?>",
        RepositoryQueryResultKind.Paged => $"global::System.Threading.Tasks.Task<global::RonSijm.RepoGen.PagedResult<{query.ResultTypeName}>>",
        RepositoryQueryResultKind.CursorPaged =>
            $"global::System.Threading.Tasks.Task<global::RonSijm.RepoGen.CursorPagedResult<{query.ResultTypeName}, {query.Cursor!.CursorTypeName}>>",
        RepositoryQueryResultKind.GroupedList =>
            $"global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<{query.ResultTypeName}>>",
        RepositoryQueryResultKind.Exists => "global::System.Threading.Tasks.Task<bool>",
        RepositoryQueryResultKind.Count => "global::System.Threading.Tasks.Task<int>",
        RepositoryQueryResultKind.Stream => $"global::System.Collections.Generic.IAsyncEnumerable<{query.ResultTypeName}>",
        _ => throw new InvalidOperationException($"Unsupported configured query result kind '{query.ResultKind}'.")
    };

    private static List<(string Type, string Name)> CreateQueryParameters(ConfiguredQueryModel query)
    {
        var parameters = query.Parameters.Select(static parameter => (parameter.TypeName, parameter.Name)).ToList();
        if (query.ResultKind == RepositoryQueryResultKind.Paged)
        {
            parameters.Add(("int", "page"));
            parameters.Add(("int", "pageSize"));
        }
        else if (query.ResultKind == RepositoryQueryResultKind.CursorPaged)
        {
            parameters.Add(($"global::RonSijm.RepoGen.CursorPageRequest<{query.Cursor!.CursorTypeName}>", "cursorPage"));
        }

        return parameters;
    }

    private static void AppendMethodParameters(
        StringBuilder builder,
        List<(string Type, string Name)> parameters,
        string indentation,
        bool includeCancellationToken)
    {
        for (var index = 0; index < parameters.Count; index++)
        {
            builder.Append(indentation).Append(parameters[index].Type).Append(' ').Append(parameters[index].Name).AppendLine(",");
        }

        if (includeCancellationToken)
        {
            builder.Append(indentation).AppendLine("global::System.Threading.CancellationToken cancellationToken = default");
        }
    }

    private static string RenderCacheOptions(ConfiguredQueryCacheModel cache)
    {
        var absolute = cache.AbsoluteExpirationTicks is long absoluteTicks
            ? $"global::System.TimeSpan.FromTicks({absoluteTicks}L)"
            : "null";
        var sliding = cache.SlidingExpirationTicks is long slidingTicks
            ? $"global::System.TimeSpan.FromTicks({slidingTicks}L)"
            : "null";
        return $"new global::RonSijm.RepoGen.RepositoryCacheEntryOptions({absolute}, {sliding})";
    }

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);

    private static void AppendProjectionMethods(
        StringBuilder builder,
        EntityRepositoryModel entity,
        ProjectionModel projection,
        string indentation)
    {
        var selectorType = Qualify(entity.Namespace, entity.EntityName + "Selector");
        var collectionSelectorType = Qualify(entity.Namespace, entity.EntityName + "CollectionSelector");
        var accessibility = entity.Accessibility == "public" && projection.Accessibility == "public"
            ? "public"
            : "internal";

        builder.Append(indentation).Append(accessibility).Append(" static global::System.Threading.Tasks.Task<")
            .Append(projection.ProjectionTypeName).Append("?> ").Append(projection.SingleMethodName).AppendLine("(");
        builder.Append(indentation).Append("    this ").Append(selectorType).AppendLine(" selector,");
        builder.Append(indentation).AppendLine("    global::System.Threading.CancellationToken cancellationToken = default)");
        builder.Append(indentation).AppendLine("{");
        var singleSelector = RenderProjectionSelector(entity, projection, collection: false);
        builder.Append(indentation).Append("    return ").Append(singleSelector)
            .Append(".ProjectToAsync(").Append(projection.ExpressionSource)
            .AppendLine(", cancellationToken);");
        builder.Append(indentation).AppendLine("}");
        builder.AppendLine();
        builder.Append(indentation).Append(accessibility).Append(" static global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<")
            .Append(projection.ProjectionTypeName).Append(">> ").Append(projection.CollectionMethodName).AppendLine("(");
        builder.Append(indentation).Append("    this ").Append(collectionSelectorType).AppendLine(" selector,");
        builder.Append(indentation).AppendLine("    global::System.Threading.CancellationToken cancellationToken = default)");
        builder.Append(indentation).AppendLine("{");
        var collectionSelector = RenderProjectionSelector(entity, projection, collection: true);
        builder.Append(indentation).Append("    return ").Append(collectionSelector)
            .Append(".ProjectToListAsync(").Append(projection.ExpressionSource)
            .AppendLine(", cancellationToken);");
        builder.Append(indentation).AppendLine("}");
        builder.AppendLine();
    }

    private static string RenderSelectorWithIncludes(ProjectionModel projection)
    {
        var selector = "selector";
        foreach (var include in projection.Includes)
        {
            selector += ".Include(" + include.ExpressionSource + ")";
        }

        return selector;
    }

    private static string RenderProjectionSelector(
        EntityRepositoryModel entity,
        ProjectionModel projection,
        bool collection)
    {
        var selector = RenderSelectorWithIncludes(projection);
        if (entity.ProjectionEnabled)
        {
            return selector;
        }

        var baseSelector = collection ? "BaseCollectionSelector" : "BaseEntitySelector";
        return $"((global::RonSijm.RepoGen.{baseSelector}<{entity.EntityTypeName}>){selector})";
    }

    private static string Qualify(string @namespace, string typeName) =>
        string.IsNullOrEmpty(@namespace) ? "global::" + typeName : "global::" + @namespace + "." + typeName;
}
